Repository DEU-Smiley/Smiley-BackEnd, pull requests merged in 2023-08, with the labels that each got.

#130 [Feat] 회원 탈퇴 기능 추가
  src/main/java/com/smiley/smileybackend/controller/UserController.java
  src/main/java/com/smiley/smileybackend/service/UserService.java
Labels: 💎 Feature, 📖 Discussion, 👁️성찬👁️

#135 [Feat] user entity change #133
  src/main/java/com/smiley/smileybackend/community/post/controller/PostApiController.java
  src/main/java/com/smiley/smileybackend/community/post/domain/Post.java
  src/main/java/com/smiley/smileybackend/community/post/domain/UserTest.java
  src/main/java/com/smiley/smileybackend/community/post/dto/PostDto.java
  src/main/java/com/smiley/smileybackend/community/post/service/PostApiService.java
  src/main/java/com/smiley/smileybackend/domain/User.java
Labels: 💎 Feature, ♻️ Refactor, 💎민수💎

#136 [Refactor] Errorexception 오류 코드 분리
  src/main/java/com/smiley/smileybackend/controller/BookingController.java
  src/main/java/com/smiley/smileybackend/controller/DailyWearTimeController.java
  src/main/java/com/smiley/smileybackend/controller/HospitalController.java
  src/main/java/com/smiley/smileybackend/controller/MagazineController.java
  src/main/java/com/smiley/smileybackend/controller/MedicineController.java
  src/main/java/com/smiley/smileybackend/controller/UserController.java
  src/main/java/com/smiley/smileybackend/controller/UserDeviceController.java
  src/main/java/com/smiley/smileybackend/domain/Booking.java
  src/main/java/com/smiley/smileybackend/dto/user/PatchBookingDto.java
  src/main/java/com/smiley/smileybackend/exception/ErrorCode.java
  src/main/java/com/smiley/smileybackend/service/BookingService.java
  src/main/resources/application.properties
Labels: 💎 Feature, ♻️ Refactor, 📖 Discussion, 👁️성찬👁️
