Repository DEU-Smiley/Smiley-BackEnd, pull requests merged in 2023-07, with the labels that each got.

#106 [refactor] 서버 코드 리펙토링
  src/main/java/com/smiley/smileybackend/controller/BookingController.java
  src/main/java/com/smiley/smileybackend/controller/DailyWearTimeController.java
  src/main/java/com/smiley/smileybackend/controller/ToothbrushStatusController.java
  src/main/java/com/smiley/smileybackend/domain/Badge.java
  src/main/java/com/smiley/smileybackend/domain/DailyWearTime.java
  src/main/java/com/smiley/smileybackend/domain/FacialResult.java
  src/main/java/com/smiley/smileybackend/domain/Hospital.java
  src/main/java/com/smiley/smileybackend/domain/Magazine.java
  src/main/java/com/smiley/smileybackend/domain/Tier.java
  src/main/java/com/smiley/smileybackend/domain/TotalExpStastics.java
  src/main/java/com/smiley/smileybackend/domain/User.java
  src/main/java/com/smiley/smileybackend/domain/UserDevice.java
  src/main/java/com/smiley/smileybackend/domain/UserMedicalInfo.java
  src/main/java/com/smiley/smileybackend/dto/response/HospitalGeocodingDto.java
  src/main/java/com/smiley/smileybackend/dto/response/MagazineDetailDto.java
  src/main/java/com/smiley/smileybackend/dto/response/ToothBrushImageDto.java
  src/main/java/com/smiley/smileybackend/dto/response/UserBookingDto.java
  src/main/java/com/smiley/smileybackend/dto/response/UserDeviceInfoDto.java
  src/main/java/com/smiley/smileybackend/dto/user/UserGeocodingDto.java
  src/main/java/com/smiley/smileybackend/dto/user/UserInfoUpdateDto.java
  src/main/java/com/smiley/smileybackend/dto/user/UserLoginDto.java
  src/main/java/com/smiley/smileybackend/exception/ErrorCode.java
  src/main/java/com/smiley/smileybackend/openapi/PublicApiController.java
  src/main/java/com/smiley/smileybackend/repository/BookingRepository.java
  src/main/java/com/smiley/smileybackend/service/BookingService.java
  src/main/java/com/smiley/smileybackend/service/DailyExpStasticsService.java
  src/main/java/com/smiley/smileybackend/service/DailyWearTimeService.java
  src/main/java/com/smiley/smileybackend/service/HospitalService.java
  src/main/java/com/smiley/smileybackend/service/MagazineService.java
  src/main/java/com/smiley/smileybackend/service/MedicineService.java
  src/main/java/com/smiley/smileybackend/service/TotalExpStasticsService.java
  src/main/java/com/smiley/smileybackend/service/UserDeviceService.java
  src/main/java/com/smiley/smileybackend/service/UserMedicalInfoService.java
  src/main/java/com/smiley/smileybackend/service/UserService.java
Labels: 🚿 Clean-Up, 👁️성찬👁️

#108 [Bug] Hospital table 생성 오류 수정
  src/main/java/com/smiley/smileybackend/domain/Hospital.java
Labels: 🐞 Bug, 👁️성찬👁️

#111 Magazine entity 변경
  src/main/java/com/smiley/smileybackend/domain/Magazine.java
  src/main/java/com/smiley/smileybackend/dto/response/MagazineDetailDto.java
  src/main/java/com/smiley/smileybackend/dto/user/ContentImgJsonDto.java
  src/main/java/com/smiley/smileybackend/dto/user/ContentLinkJsonDto.java
  src/main/java/com/smiley/smileybackend/service/MagazineService.java
Labels: ♻️ Refactor, 📖 Discussion, 👁️성찬👁️

#114 [Refactor] 페이징 기능 추가
  src/main/java/com/smiley/smileybackend/controller/MagazineController.java
  src/main/java/com/smiley/smileybackend/repository/MagazineRepository.java
  src/main/java/com/smiley/smileybackend/service/MagazineService.java
Labels: ♻️ Refactor, 👁️성찬👁️

#121 refactor : 칫솔모 검사기능 Linux 환경 적용(#119)
  META-INF/MANIFEST.MF
  src/main/java/com/smiley/smileybackend/SmileyBackEndApplication.java
  src/main/java/com/smiley/smileybackend/service/ToothBrushStatusService.java
  src/main/resources/application-dep1.properties
  src/main/resources/application-dep2.properties
  src/main/resources/application-path.properties
  src/main/resources/application.properties
Labels: ♻️ Refactor, 🚬김준🚬

#125 [FEAT] 예약 기능 구현
  src/main/java/com/smiley/smileybackend/controller/BookingController.java
  src/main/java/com/smiley/smileybackend/domain/Booking.java
  src/main/java/com/smiley/smileybackend/dto/response/UserBookingDto.java
  src/main/java/com/smiley/smileybackend/dto/response/UserDeviceInfoDto.java
  src/main/java/com/smiley/smileybackend/dto/user/BookingCancelInfoDto.java
  src/main/java/com/smiley/smileybackend/dto/user/BookingInfoDto.java
  src/main/java/com/smiley/smileybackend/dto/user/UserMemoDto.java
  src/main/java/com/smiley/smileybackend/exception/ErrorCode.java
  src/main/java/com/smiley/smileybackend/repository/BookingRepository.java
  src/main/java/com/smiley/smileybackend/service/BookingService.java
Labels: 💎 Feature, 👁️성찬👁️

#123 [Feat] 커뮤니티 게시글 CRUD 기능
  src/main/java/com/smiley/smileybackend/community/post/controller/PostApiController.java
  src/main/java/com/smiley/smileybackend/community/post/domain/Post.java
  src/main/java/com/smiley/smileybackend/community/post/domain/UserTest.java
  src/main/java/com/smiley/smileybackend/community/post/domain/enums/Category.java
  src/main/java/com/smiley/smileybackend/community/post/dto/PostDto.java
  src/main/java/com/smiley/smileybackend/community/post/repository/CommunityPostRepository.java
  src/main/java/com/smiley/smileybackend/community/post/service/PostApiService.java
Labels: 💎 Feature, 💎민수💎
